# Generated by Django 5.2.5 on 2025-09-10 04:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSemaforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la configuración', max_length=100, unique=True, verbose_name='Nombre de Configuración')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de esta configuración', verbose_name='Descripción')),
                ('tipo_calculo', models.CharField(choices=[('dias_restantes', 'Por Días Restantes'), ('porcentaje_tiempo', 'Por Porcentaje de Tiempo Transcurrido'), ('estado_cuña', 'Por Estado de la Cuña'), ('combinado', 'Combinado (Estado + Tiempo)')], default='combinado', help_text='Método de cálculo para determinar el color del semáforo', max_length=20, verbose_name='Tipo de Cálculo')),
                ('dias_verde_min', models.PositiveIntegerField(default=15, help_text='Días mínimos restantes para mostrar verde', verbose_name='Días Mínimos para Verde')),
                ('dias_amarillo_min', models.PositiveIntegerField(default=7, help_text='Días mínimos restantes para mostrar amarillo (menos que esto es rojo)', verbose_name='Días Mínimos para Amarillo')),
                ('porcentaje_verde_max', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Porcentaje máximo de tiempo transcurrido para mostrar verde', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje Máximo para Verde')),
                ('porcentaje_amarillo_max', models.DecimalField(decimal_places=2, default=Decimal('85.00'), help_text='Porcentaje máximo de tiempo transcurrido para mostrar amarillo', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje Máximo para Amarillo')),
                ('estados_verde', models.JSONField(default=list, help_text='Lista de estados de cuña que muestran verde', verbose_name='Estados Verde')),
                ('estados_amarillo', models.JSONField(default=list, help_text='Lista de estados de cuña que muestran amarillo', verbose_name='Estados Amarillo')),
                ('estados_rojo', models.JSONField(default=list, help_text='Lista de estados de cuña que muestran rojo', verbose_name='Estados Rojo')),
                ('estados_gris', models.JSONField(default=list, help_text='Lista de estados de cuña que muestran gris', verbose_name='Estados Gris')),
                ('enviar_alertas', models.BooleanField(default=True, help_text='Si enviar alertas automáticas cuando cambia el estado', verbose_name='Enviar Alertas')),
                ('alertas_solo_empeoramiento', models.BooleanField(default=True, help_text='Solo alertar cuando el estado empeora (verde->amarillo->rojo)', verbose_name='Alertas Solo por Empeoramiento')),
                ('is_active', models.BooleanField(default=False, help_text='Si esta configuración está activa (solo una puede estar activa)', verbose_name='Activa')),
                ('is_default', models.BooleanField(default=False, help_text='Si esta es la configuración por defecto', verbose_name='Por Defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_semaforo_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Configuración de Semáforo',
                'verbose_name_plural': 'Configuraciones de Semáforo',
                'ordering': ['-is_active', '-is_default', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoSemaforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_actual', models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo'), ('gris', 'Gris')], help_text='Color actual del semáforo', max_length=10, verbose_name='Color Actual')),
                ('color_anterior', models.CharField(blank=True, choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo'), ('gris', 'Gris')], help_text='Color anterior del semáforo', max_length=10, null=True, verbose_name='Color Anterior')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', help_text='Prioridad basada en el estado actual', max_length=10, verbose_name='Prioridad')),
                ('dias_restantes', models.IntegerField(blank=True, help_text='Días restantes hasta la fecha fin', null=True, verbose_name='Días Restantes')),
                ('porcentaje_tiempo_transcurrido', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje del tiempo total que ha transcurrido', max_digits=5, null=True, verbose_name='Porcentaje Tiempo Transcurrido')),
                ('razon_color', models.TextField(blank=True, help_text='Explicación de por qué se asignó este color', verbose_name='Razón del Color')),
                ('metadatos_calculo', models.JSONField(default=dict, help_text='Información adicional sobre el cálculo realizado', verbose_name='Metadatos del Cálculo')),
                ('requiere_alerta', models.BooleanField(default=False, help_text='Si se debe enviar una alerta por este estado', verbose_name='Requiere Alerta')),
                ('alerta_enviada', models.BooleanField(default=False, help_text='Si ya se envió la alerta para este estado', verbose_name='Alerta Enviada')),
                ('fecha_alerta_enviada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Alerta Enviada')),
                ('calculado_en', models.DateTimeField(auto_now=True, verbose_name='Calculado en')),
                ('ultimo_calculo', models.DateTimeField(auto_now=True, verbose_name='Último Cálculo')),
                ('configuracion_utilizada', models.ForeignKey(help_text='Configuración de semáforo que se utilizó para este cálculo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic_light_system.configuracionsemaforo', verbose_name='Configuración Utilizada')),
                ('cuña', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_semaforo', to='content_management.cuñapublicitaria', verbose_name='Cuña Publicitaria')),
            ],
            options={
                'verbose_name': 'Estado de Semáforo',
                'verbose_name_plural': 'Estados de Semáforo',
                'ordering': ['-ultimo_calculo'],
            },
        ),
        migrations.CreateModel(
            name='AlertaSemaforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('cambio_estado', 'Cambio de Estado'), ('vencimiento_proximo', 'Vencimiento Próximo'), ('estado_critico', 'Estado Crítico'), ('revision_requerida', 'Revisión Requerida'), ('configuracion_cambio', 'Cambio de Configuración')], max_length=20, verbose_name='Tipo de Alerta')),
                ('severidad', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], default='warning', max_length=10, verbose_name='Severidad')),
                ('titulo', models.CharField(help_text='Título descriptivo de la alerta', max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(help_text='Mensaje detallado de la alerta', verbose_name='Mensaje')),
                ('roles_destino', models.JSONField(default=list, help_text='Lista de roles que deben recibir esta alerta', verbose_name='Roles Destino')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('error', 'Error al Enviar'), ('ignorada', 'Ignorada')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('enviar_email', models.BooleanField(default=True, verbose_name='Enviar por Email')),
                ('enviar_sms', models.BooleanField(default=False, verbose_name='Enviar por SMS')),
                ('enviar_push', models.BooleanField(default=True, verbose_name='Enviar Push Notification')),
                ('mostrar_dashboard', models.BooleanField(default=True, verbose_name='Mostrar en Dashboard')),
                ('fecha_programada', models.DateTimeField(blank=True, help_text='Fecha programada para envío (si es diferente de creación)', null=True, verbose_name='Fecha Programada')),
                ('fecha_enviada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Enviada')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Fecha hasta la cual la alerta es relevante', null=True, verbose_name='Fecha de Vencimiento')),
                ('reintentos', models.PositiveIntegerField(default=0, help_text='Número de reintentos de envío', verbose_name='Reintentos')),
                ('max_reintentos', models.PositiveIntegerField(default=3, verbose_name='Máximo Reintentos')),
                ('error_mensaje', models.TextField(blank=True, help_text='Último mensaje de error si falló el envío', verbose_name='Mensaje de Error')),
                ('metadatos', models.JSONField(default=dict, help_text='Información adicional sobre la alerta', verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('cuña', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_semaforo', to='content_management.cuñapublicitaria', verbose_name='Cuña Publicitaria')),
                ('usuarios_destino', models.ManyToManyField(blank=True, related_name='alertas_semaforo_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Destino')),
                ('estado_semaforo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traffic_light_system.estadosemaforo', verbose_name='Estado Semáforo')),
            ],
            options={
                'verbose_name': 'Alerta de Semáforo',
                'verbose_name_plural': 'Alertas de Semáforo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoSemaforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_anterior', models.CharField(blank=True, choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo'), ('gris', 'Gris')], max_length=10, null=True, verbose_name='Color Anterior')),
                ('color_nuevo', models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo'), ('gris', 'Gris')], max_length=10, verbose_name='Color Nuevo')),
                ('prioridad_anterior', models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10, null=True, verbose_name='Prioridad Anterior')),
                ('prioridad_nueva', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10, verbose_name='Prioridad Nueva')),
                ('razon_cambio', models.TextField(help_text='Explicación de por qué cambió el estado', verbose_name='Razón del Cambio')),
                ('dias_restantes', models.IntegerField(blank=True, null=True, verbose_name='Días Restantes')),
                ('porcentaje_tiempo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje Tiempo Transcurrido')),
                ('alerta_generada', models.BooleanField(default=False, help_text='Si se generó una alerta para este cambio', verbose_name='Alerta Generada')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('metadatos', models.JSONField(default=dict, verbose_name='Metadatos')),
                ('configuracion_utilizada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic_light_system.configuracionsemaforo', verbose_name='Configuración Utilizada')),
                ('cuña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_semaforo', to='content_management.cuñapublicitaria', verbose_name='Cuña Publicitaria')),
                ('usuario_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Provocó el Cambio')),
            ],
            options={
                'verbose_name': 'Historial de Estado Semáforo',
                'verbose_name_plural': 'Historial de Estados Semáforo',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='ResumenEstadosSemaforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('dia', 'Diario'), ('semana', 'Semanal'), ('mes', 'Mensual')], max_length=10, verbose_name='Período')),
                ('fecha', models.DateField(help_text='Fecha del resumen (día, inicio de semana, o inicio de mes)', verbose_name='Fecha')),
                ('total_cuñas', models.PositiveIntegerField(default=0, verbose_name='Total Cuñas')),
                ('cuñas_verde', models.PositiveIntegerField(default=0, verbose_name='Cuñas Verde')),
                ('cuñas_amarillo', models.PositiveIntegerField(default=0, verbose_name='Cuñas Amarillo')),
                ('cuñas_rojo', models.PositiveIntegerField(default=0, verbose_name='Cuñas Rojo')),
                ('cuñas_gris', models.PositiveIntegerField(default=0, verbose_name='Cuñas Gris')),
                ('cuñas_prioridad_baja', models.PositiveIntegerField(default=0, verbose_name='Prioridad Baja')),
                ('cuñas_prioridad_media', models.PositiveIntegerField(default=0, verbose_name='Prioridad Media')),
                ('cuñas_prioridad_alta', models.PositiveIntegerField(default=0, verbose_name='Prioridad Alta')),
                ('cuñas_prioridad_critica', models.PositiveIntegerField(default=0, verbose_name='Prioridad Crítica')),
                ('alertas_generadas', models.PositiveIntegerField(default=0, verbose_name='Alertas Generadas')),
                ('cambios_estado', models.PositiveIntegerField(default=0, verbose_name='Cambios de Estado')),
                ('porcentaje_verde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje Verde')),
                ('porcentaje_problemas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de cuñas en amarillo o rojo', max_digits=5, verbose_name='Porcentaje con Problemas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('configuracion_utilizada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic_light_system.configuracionsemaforo', verbose_name='Configuración Utilizada')),
            ],
            options={
                'verbose_name': 'Resumen Estados Semáforo',
                'verbose_name_plural': 'Resúmenes Estados Semáforo',
                'ordering': ['-fecha', '-periodo'],
            },
        ),
        migrations.AddIndex(
            model_name='estadosemaforo',
            index=models.Index(fields=['color_actual', 'prioridad'], name='traffic_lig_color_a_fa9e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='estadosemaforo',
            index=models.Index(fields=['requiere_alerta', 'alerta_enviada'], name='traffic_lig_requier_bb0ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='estadosemaforo',
            index=models.Index(fields=['ultimo_calculo'], name='traffic_lig_ultimo__43a103_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasemaforo',
            index=models.Index(fields=['tipo_alerta', 'severidad'], name='traffic_lig_tipo_al_932fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasemaforo',
            index=models.Index(fields=['estado', 'fecha_programada'], name='traffic_lig_estado_cd1918_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasemaforo',
            index=models.Index(fields=['cuña', 'created_at'], name='traffic_lig_cuña_id_fe7910_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasemaforo',
            index=models.Index(fields=['fecha_vencimiento'], name='traffic_lig_fecha_v_6e05c8_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestadosemaforo',
            index=models.Index(fields=['cuña', 'fecha_cambio'], name='traffic_lig_cuña_id_18106b_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestadosemaforo',
            index=models.Index(fields=['color_nuevo', 'fecha_cambio'], name='traffic_lig_color_n_83c26d_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestadosemaforo',
            index=models.Index(fields=['alerta_generada'], name='traffic_lig_alerta__565188_idx'),
        ),
        migrations.AddIndex(
            model_name='resumenestadossemaforo',
            index=models.Index(fields=['periodo', 'fecha'], name='traffic_lig_periodo_7f9d73_idx'),
        ),
        migrations.AddIndex(
            model_name='resumenestadossemaforo',
            index=models.Index(fields=['fecha'], name='traffic_lig_fecha_b8178a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resumenestadossemaforo',
            unique_together={('periodo', 'fecha')},
        ),
    ]
