# Generated by Django 5.2.5 on 2025-10-30 19:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenToma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la orden (generado automáticamente)', max_length=20, unique=True, verbose_name='Código')),
                ('nombre_cliente', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('ruc_dni_cliente', models.CharField(max_length=20, verbose_name='RUC/DNI del Cliente')),
                ('empresa_cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa')),
                ('ciudad_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('direccion_cliente', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('detalle_productos', models.TextField(help_text='Descripción de los productos o servicios solicitados', verbose_name='Detalle de Productos/Servicios')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total de la orden', max_digits=10, verbose_name='Total')),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('validado', 'Validado'), ('en_produccion', 'En Producción'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='generado', help_text='Estado actual de la orden', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', help_text='Prioridad de la orden', max_length=10, verbose_name='Prioridad')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la orden', verbose_name='Observaciones')),
                ('fecha_orden', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Orden')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_toma', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_completadas', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
                ('vendedor_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol': 'vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_vendidas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado')),
            ],
            options={
                'verbose_name': 'Orden de Toma',
                'verbose_name_plural': 'Órdenes de Toma',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creada', 'Creada'), ('editada', 'Editada'), ('validada', 'Validada'), ('produccion', 'Enviada a Producción'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='Acción')),
                ('descripcion', models.TextField(help_text='Descripción detallada del cambio realizado', verbose_name='Descripción')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado anterior de los campos modificados', null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Nuevo estado de los campos modificados', null=True, verbose_name='Datos Nuevos')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='orders.ordentoma', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Historial de Orden',
                'verbose_name_plural': 'Historial de Órdenes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='ordentoma',
            index=models.Index(fields=['estado', 'fecha_orden'], name='orders_orde_estado_4653d6_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentoma',
            index=models.Index(fields=['cliente', 'estado'], name='orders_orde_cliente_20e463_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentoma',
            index=models.Index(fields=['vendedor_asignado', 'estado'], name='orders_orde_vendedo_8f8b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentoma',
            index=models.Index(fields=['codigo'], name='orders_orde_codigo_e5427f_idx'),
        ),
    ]
