# Generated by Django 5.2.5 on 2025-11-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentoma',
            name='descripcion_breve',
            field=models.TextField(blank=True, help_text='Descripción breve del trabajo a realizar', null=True, verbose_name='Descripción Breve'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='equipo_asignado',
            field=models.TextField(blank=True, help_text='Equipo técnico asignado para la producción', null=True, verbose_name='Equipo Asignado'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='fecha_produccion_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Producción'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='fecha_produccion_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Producción'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Fin'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Inicio'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='locaciones',
            field=models.TextField(blank=True, help_text='Locaciones donde se realizará la toma', null=True, verbose_name='Locaciones'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='observaciones_completado',
            field=models.TextField(blank=True, help_text='Observaciones al completar la toma', null=True, verbose_name='Observaciones de Completado'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='proyecto_campania',
            field=models.CharField(blank=True, help_text='Nombre del proyecto o campaña', max_length=255, null=True, verbose_name='Proyecto/Campaña'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='recursos_necesarios',
            field=models.TextField(blank=True, help_text='Recursos adicionales necesarios', null=True, verbose_name='Recursos Necesarios'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='titulo_material',
            field=models.CharField(blank=True, help_text='Título del material a producir', max_length=255, null=True, verbose_name='Título del Material'),
        ),
        migrations.AlterField(
            model_name='ordentoma',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('en_produccion', 'En Producción'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual de la orden', max_length=20, verbose_name='Estado'),
        ),
    ]
