# Generated by Django 5.2.5 on 2025-11-04 20:15

import apps.orders.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordentoma_descripcion_breve_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo (ej: Orden Toma Video 2025)', max_length=200, verbose_name='Nombre de la Plantilla')),
                ('tipo_orden', models.CharField(choices=[('toma_video', 'Toma de Video'), ('produccion_audio', 'Producción de Audio'), ('edicion_video', 'Edición de Video'), ('produccion_completa', 'Producción Completa'), ('otro', 'Otro')], default='toma_video', help_text='Tipo de orden que representa esta plantilla', max_length=50, verbose_name='Tipo de Orden')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de cuándo usar esta plantilla', verbose_name='Descripción')),
                ('archivo_plantilla', models.FileField(help_text='Archivo Word con marcadores: {{NOMBRE_CLIENTE}}, {{RUC_DNI}}, etc.', upload_to=apps.orders.models.orden_template_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Archivo de Plantilla (.docx)')),
                ('variables_disponibles', models.JSONField(blank=True, default=dict, help_text='Variables que se reemplazan en la plantilla', verbose_name='Variables Disponibles')),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones sobre cómo usar esta plantilla', verbose_name='Instrucciones de Uso')),
                ('version', models.CharField(default='1.0', help_text='Versión de la plantilla', max_length=20, verbose_name='Versión')),
                ('is_active', models.BooleanField(default=True, help_text='Si la plantilla está activa', verbose_name='Activa')),
                ('is_default', models.BooleanField(default=False, help_text='Si es la plantilla predeterminada', verbose_name='Plantilla por Defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_orden_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Plantilla de Orden',
                'verbose_name_plural': 'Plantillas de Orden',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Número de Orden')),
                ('archivo_orden_pdf', models.FileField(blank=True, null=True, upload_to=apps.orders.models.orden_output_path, verbose_name='Orden en PDF')),
                ('archivo_orden_validada', models.FileField(blank=True, help_text='PDF subido manualmente después de validar', null=True, upload_to=apps.orders.models.orden_validada_path, verbose_name='Orden Validada (Subida)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generada', 'Generada'), ('impresa', 'Impresa'), ('validada', 'Validada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('datos_generacion', models.JSONField(default=dict, verbose_name='Datos de Generación')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('fecha_impresion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Impresión')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas_por', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('impreso_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_impresas_por', to=settings.AUTH_USER_MODEL, verbose_name='Impreso por')),
                ('orden_toma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_generadas', to='orders.ordentoma', verbose_name='Orden de Toma')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_validadas_por', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
                ('plantilla_usada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='orders.plantillaorden', verbose_name='Plantilla Utilizada')),
            ],
            options={
                'verbose_name': 'Orden Generada',
                'verbose_name_plural': 'Órdenes Generadas',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
