# Generated by Django 5.2.5 on 2025-11-07 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_plantillaorden_ordengenerada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la orden de producción (generado automáticamente)', max_length=20, unique=True, verbose_name='Código')),
                ('nombre_cliente', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('ruc_dni_cliente', models.CharField(max_length=20, verbose_name='RUC/DNI del Cliente')),
                ('empresa_cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa')),
                ('proyecto_campania', models.CharField(help_text='Nombre del proyecto o campaña', max_length=255, verbose_name='Proyecto/Campaña')),
                ('titulo_material', models.CharField(help_text='Título del material a producir', max_length=255, verbose_name='Título del Material')),
                ('descripcion_breve', models.TextField(help_text='Descripción breve del trabajo a realizar', verbose_name='Descripción Breve')),
                ('tipo_produccion', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('edicion', 'Edición'), ('animacion', 'Animación'), ('mixto', 'Mixto')], default='video', max_length=50, verbose_name='Tipo de Producción')),
                ('especificaciones_tecnicas', models.TextField(blank=True, help_text='Formatos, resoluciones, codecs, etc.', null=True, verbose_name='Especificaciones Técnicas')),
                ('fecha_inicio_planeada', models.DateField(verbose_name='Fecha Inicio Planeada')),
                ('fecha_fin_planeada', models.DateField(verbose_name='Fecha Fin Planeada')),
                ('fecha_inicio_real', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Real')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Real')),
                ('equipo_asignado', models.TextField(help_text='Equipo técnico asignado para la producción', verbose_name='Equipo Asignado')),
                ('recursos_necesarios', models.TextField(blank=True, help_text='Recursos adicionales necesarios', null=True, verbose_name='Recursos Necesarios')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_produccion', 'En Producción'), ('completado', 'Completado'), ('validado', 'Validado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('archivos_entregables', models.TextField(blank=True, help_text='Lista de archivos a entregar', null=True, verbose_name='Archivos Entregables')),
                ('observaciones_produccion', models.TextField(blank=True, null=True, verbose_name='Observaciones de Producción')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion_completadas', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('orden_toma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to='orders.ordentoma', verbose_name='Orden de Toma')),
                ('productor_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol': 'productor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_producidas', to=settings.AUTH_USER_MODEL, verbose_name='Productor Asignado')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creada', 'Creada'), ('editada', 'Editada'), ('iniciada', 'Producción Iniciada'), ('completada', 'Completada'), ('validada', 'Validada'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='Acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='orders.ordenproduccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Historial de Orden de Producción',
                'verbose_name_plural': 'Historial de Órdenes de Producción',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='ordenproduccion',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='orders_orde_estado_fcdcee_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenproduccion',
            index=models.Index(fields=['orden_toma', 'estado'], name='orders_orde_orden_t_7937f2_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenproduccion',
            index=models.Index(fields=['codigo'], name='orders_orde_codigo_12d44f_idx'),
        ),
    ]
