# Generated by Django 5.2.5 on 2025-11-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordenproduccion_historialordenproduccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordengenerada',
            name='orden_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_generadas_produccion', to='orders.ordenproduccion', verbose_name='Orden de Producción'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='archivo_orden_firmada',
            field=models.FileField(blank=True, help_text='PDF de la orden de producción firmada por el cliente', null=True, upload_to='ordenes_produccion_firmadas/', verbose_name='Orden Firmada'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_subida_firmada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Subida Firmada'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='plantilla_orden',
            field=models.ForeignKey(blank=True, help_text='Plantilla Word para generar la orden de producción', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.plantillaorden', verbose_name='Plantilla de Orden de Producción'),
        ),
    ]
