# Generated by Django 5.2.5 on 2026-01-04 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordengenerada_orden_produccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='requiere_audio',
            field=models.BooleanField(default=False, verbose_name='Requiere Audio'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='requiere_logo',
            field=models.BooleanField(default=False, verbose_name='Requiere Logo'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='requiere_tomas',
            field=models.BooleanField(default=False, verbose_name='Requiere Tomas'),
        ),
        migrations.AlterField(
            model_name='ordengenerada',
            name='orden_toma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_generadas', to='orders.ordentoma', verbose_name='Orden de Toma'),
        ),
        migrations.AlterField(
            model_name='plantillaorden',
            name='tipo_orden',
            field=models.CharField(choices=[('toma_video', 'Toma de Video'), ('produccion_audio', 'Producción de Audio'), ('edicion_video', 'Edición de Video'), ('produccion_completa', 'Producción Completa'), ('autorizacion', 'Autorización de Transmisión'), ('suspension', 'Suspensión de Transmisión'), ('otro', 'Otro')], default='toma_video', help_text='Tipo de orden que representa esta plantilla', max_length=50, verbose_name='Tipo de Orden'),
        ),
        migrations.CreateModel(
            name='OrdenAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único (generado automáticamente)', max_length=20, unique=True, verbose_name='Código')),
                ('nombre_cliente', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('empresa_cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa')),
                ('ruc_dni_cliente', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC/DNI')),
                ('campania', models.CharField(help_text='Nombre de la campaña o spot a transmitir (ej: MUNDO MÁGICO)', max_length=255, verbose_name='Campaña / Publicidad')),
                ('detalle_transmision', models.TextField(help_text='Detalle de cómo se transmitirá (ej: Un Spot en noticiero, Dos en programación regular...)', verbose_name='Detalle de Transmisión')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(limit_choices_to={'rol': 'vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_vendidas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Orden de Autorización',
                'verbose_name_plural': 'Órdenes de Autorización',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ordengenerada',
            name='orden_autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_generadas_autorizacion', to='orders.ordenautorizacion', verbose_name='Orden de Autorización'),
        ),
        migrations.CreateModel(
            name='OrdenSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre_cliente', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('campania', models.CharField(help_text='Nombre de la publicidad que sale del aire', max_length=255, verbose_name='Campaña / Publicidad')),
                ('fecha_salida_aire', models.DateField(help_text='Fecha efectiva de suspensión', verbose_name='Fecha Salida del Aire')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de Suspensión')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('autorizacion_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensiones', to='orders.ordenautorizacion', verbose_name='Autorización Relacionada')),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='suspensiones', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensiones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Suspensión',
                'verbose_name_plural': 'Órdenes de Suspensión',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ordengenerada',
            name='orden_suspension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_generadas_suspension', to='orders.ordensuspension', verbose_name='Orden de Suspensión'),
        ),
    ]
