# Generated by Django 5.2.5 on 2026-01-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0009_alter_contratogenerado_estado'),
        ('orders', '0006_ordenproduccion_requiere_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenautorizacion',
            name='orden_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones', to='orders.ordenproduccion', verbose_name='Orden de Producción Relacionada'),
        ),
        migrations.AddField(
            model_name='ordensuspension',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensiones', to='content_management.contratogenerado', verbose_name='Contrato o Cuña a suspender'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_produccion', 'En Producción'), ('completado', 'Completado'), ('validado', 'Validado'), ('autorizado', 'Autorizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
