# Generated by Django 5.2.5 on 2026-01-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordenautorizacion_orden_produccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenautorizacion',
            name='archivo_firmado',
            field=models.FileField(blank=True, help_text='Documento firmado que valida la autorización', null=True, upload_to='ordenes_autorizacion_firmadas/', verbose_name='Orden Firmada'),
        ),
        migrations.AddField(
            model_name='ordenautorizacion',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma'),
        ),
    ]
