# Generated by Django 5.2.5 on 2026-01-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordenautorizacion_archivo_firmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordensuspension',
            name='archivo_firmado',
            field=models.FileField(blank=True, help_text='Documento firmado que valida la suspensión', null=True, upload_to='ordenes_suspension_firmadas/', verbose_name='Orden Firmada'),
        ),
        migrations.AddField(
            model_name='ordensuspension',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma'),
        ),
    ]
