# Generated by Django 5.2.5 on 2026-01-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ordensuspension_archivo_firmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentoma',
            name='archivo_orden_firmada',
            field=models.FileField(blank=True, help_text='PDF de la orden de toma firmada por el cliente', null=True, upload_to='ordenes_toma_firmadas/', verbose_name='Orden Firmada'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='fecha_subida_firmada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Subida Firmada'),
        ),
    ]
