# Generated by Django 5.2.5 on 2026-01-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_ordentoma_archivo_orden_firmada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentoma',
            name='incluye_audio',
            field=models.BooleanField(default=False, verbose_name='Incluye Audio'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='incluye_logo',
            field=models.BooleanField(default=False, verbose_name='Incluye Logo'),
        ),
        migrations.AddField(
            model_name='ordentoma',
            name='incluye_tomas',
            field=models.BooleanField(default=False, verbose_name='Incluye Tomas'),
        ),
    ]
