# Generated by Django 5.2.5 on 2025-11-17 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_management', '0008_agregar_vendedor_a_contratos'),
        ('programacion_canal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUbicacionPublicitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('duracion_maxima', models.DurationField(verbose_name='Duración Máxima')),
                ('prioridad', models.IntegerField(default=1, verbose_name='Prioridad')),
            ],
            options={
                'verbose_name': 'Tipo de Ubicación Publicitaria',
                'verbose_name_plural': 'Tipos de Ubicaciones Publicitarias',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrillaPublicitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('total_cuñas_programadas', models.PositiveIntegerField(default=0, verbose_name='Total Cuñas Programadas')),
                ('total_ingresos_proyectados', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ingresos Proyectados')),
                ('generada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generada por')),
                ('programacion_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grillas_publicitarias', to='programacion_canal.programacionsemanal', verbose_name='Programación Semanal')),
            ],
            options={
                'verbose_name': 'Grilla Publicitaria',
                'verbose_name_plural': 'Grillas Publicitarias',
                'ordering': ['-programacion_semanal__fecha_inicio_semana'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionPublicitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('hora_inicio_relativa', models.DurationField(help_text='Tiempo desde el inicio del bloque (HH:MM:SS)', verbose_name='Hora Inicio Relativa')),
                ('duracion_disponible', models.DurationField(help_text='Duración máxima para publicidad', verbose_name='Duración Disponible')),
                ('capacidad_cuñas', models.PositiveIntegerField(default=1, verbose_name='Capacidad de Cuñas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('bloque_programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_publicitarias', to='programacion_canal.bloqueprogramacion', verbose_name='Bloque de Programación')),
                ('tipo_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='grilla_publicitaria.tipoubicacionpublicitaria', verbose_name='Tipo de Ubicación')),
            ],
            options={
                'verbose_name': 'Ubicación Publicitaria',
                'verbose_name_plural': 'Ubicaciones Publicitarias',
                'ordering': ['bloque_programacion', 'hora_inicio_relativa'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionCuña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('hora_emision', models.TimeField(verbose_name='Hora de Emisión')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('transmitida', 'Transmitida'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado')),
                ('orden_en_ubicacion', models.PositiveIntegerField(default=1, verbose_name='Orden en Ubicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cuña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='content_management.cuñapublicitaria', verbose_name='Cuña Publicitaria')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='grilla_publicitaria.ubicacionpublicitaria', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Asignación de Cuña',
                'verbose_name_plural': 'Asignaciones de Cuñas',
                'ordering': ['fecha_emision', 'hora_emision', 'ubicacion', 'orden_en_ubicacion'],
            },
        ),
    ]
