# Generated by Django 5.2.5 on 2025-11-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grilla_publicitaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacionpublicitaria',
            name='tipo_ubicacion',
        ),
        migrations.AddField(
            model_name='ubicacionpublicitaria',
            name='tipo_pausa',
            field=models.CharField(choices=[('corta', 'Pausa Corta (30 seg)'), ('media', 'Pausa Media (60 seg)'), ('larga', 'Pausa Larga (90 seg)'), ('especial', 'Pausa Especial (120 seg)')], default='corta', max_length=20, verbose_name='Tipo de Pausa'),
        ),
        migrations.AlterField(
            model_name='ubicacionpublicitaria',
            name='capacidad_cuñas',
            field=models.PositiveIntegerField(default=3, verbose_name='Capacidad de Cuñas'),
        ),
    ]
