# Generated by Django 5.2.5 on 2025-11-15 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Programa')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('noticiero', 'Noticiero'), ('entretenimiento', 'Entretenimiento'), ('deportivo', 'Deportivo'), ('cultural', 'Cultural'), ('educativo', 'Educativo'), ('musical', 'Musical'), ('variedades', 'Variedades'), ('pelicula', 'Película'), ('serie', 'Serie'), ('documental', 'Documental'), ('otros', 'Otros')], default='entretenimiento', max_length=20, verbose_name='Tipo')),
                ('duracion_estandar', models.DurationField(help_text='Duración típica del programa (HH:MM:SS)', verbose_name='Duración Estándar')),
                ('codigo', models.CharField(help_text='Código único del programa', max_length=20, unique=True, verbose_name='Código')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_produccion', 'En Producción')], default='activo', max_length=15, verbose_name='Estado')),
                ('color', models.CharField(default='#3498db', help_text='Color hexadecimal para el calendario', max_length=7, verbose_name='Color en calendario')),
                ('es_serie', models.BooleanField(default=False, verbose_name='Es una serie')),
                ('temporada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Temporada')),
                ('episodio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Episodio')),
                ('titulo_episodio', models.CharField(blank=True, max_length=200, verbose_name='Título del Episodio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Programación')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('fecha_inicio_semana', models.DateField(help_text='Lunes de la semana programada', verbose_name='Inicio de Semana')),
                ('fecha_fin_semana', models.DateField(help_text='Domingo de la semana programada', verbose_name='Fin de Semana')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('publicada', 'Publicada'), ('en_emision', 'En Emisión'), ('completada', 'Completada')], default='borrador', max_length=15, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_semanales_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Programación Semanal',
                'verbose_name_plural': 'Programaciones Semanales',
                'ordering': ['-fecha_inicio_semana'],
            },
        ),
        migrations.CreateModel(
            name='BloqueProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('duracion_real', models.DurationField(help_text='Duración real en emisión (HH:MM:SS)', verbose_name='Duración Real')),
                ('es_repeticion', models.BooleanField(default=False, verbose_name='Es Repetición')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre este bloque', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_programacion', to='programacion_canal.programa', verbose_name='Programa')),
                ('programacion_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='programacion_canal.programacionsemanal', verbose_name='Programación Semanal')),
            ],
            options={
                'verbose_name': 'Bloque de Programación',
                'verbose_name_plural': 'Bloques de Programación',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('programacion_semanal', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
