# Generated by Django 5.2.5 on 2025-11-20 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_canal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#3498db', help_text='Color hexadecimal para identificar la categoría', max_length=7, verbose_name='Color')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Categoría de Programa',
                'verbose_name_plural': 'Categorías de Programas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='programa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='programacion_canal.categoriaprograma', verbose_name='Categoría'),
        ),
    ]
