# Generated by Django 5.2.5 on 2025-11-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_canal', '0002_categoriaprograma_programa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaprograma',
            name='color',
            field=models.CharField(blank=True, default='#3498db', help_text='Color hexadecimal para identificar la categoría', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='categoriaprograma',
            name='orden',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Orden de visualización', null=True, verbose_name='Orden'),
        ),
    ]
