# Generated by Django 5.2.5 on 2025-11-12 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('total_contratos', models.IntegerField(default=0, verbose_name='Total Contratos')),
                ('contratos_activos', models.IntegerField(default=0, verbose_name='Contratos Activos')),
                ('contratos_pendientes', models.IntegerField(default=0, verbose_name='Contratos Pendientes')),
                ('contratos_por_vencer', models.IntegerField(default=0, verbose_name='Contratos por Vencer')),
                ('contratos_vencidos', models.IntegerField(default=0, verbose_name='Contratos Vencidos')),
                ('contratos_cancelados', models.IntegerField(default=0, verbose_name='Contratos Cancelados')),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos Totales')),
                ('ingresos_activos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos Activos')),
            ],
            options={
                'verbose_name': 'Dashboard Contratos',
                'verbose_name_plural': 'Dashboards Contratos',
            },
        ),
        migrations.CreateModel(
            name='ReporteContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('tipo_reporte', models.CharField(choices=[('estado_contratos', 'Reporte por Estado de Contratos'), ('contratos_vencimiento', 'Reporte por Vencimiento'), ('ingresos_contratos', 'Reporte de Ingresos por Contratos'), ('contratos_cliente', 'Reporte por Cliente')], max_length=50, verbose_name='Tipo de Reporte')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parámetros del Reporte')),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='reportes/contratos/', verbose_name='Archivo Generado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Contratos',
                'verbose_name_plural': 'Reportes de Contratos',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
