# Generated by Django 5.2.5 on 2025-11-15 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_analytics', '0002_reportevendedores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPartesMortuorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('total_partes', models.IntegerField(default=0, verbose_name='Total Partes')),
                ('partes_programados', models.IntegerField(default=0, verbose_name='Partes Programados')),
                ('partes_transmitidos', models.IntegerField(default=0, verbose_name='Partes Transmitidos')),
                ('partes_urgentes', models.IntegerField(default=0, verbose_name='Partes Urgentes')),
                ('partes_pendientes', models.IntegerField(default=0, verbose_name='Partes Pendientes')),
                ('partes_cancelados', models.IntegerField(default=0, verbose_name='Partes Cancelados')),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos Totales')),
                ('ingresos_mensuales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos Mensuales')),
            ],
            options={
                'verbose_name': 'Dashboard Partes Mortuorios',
                'verbose_name_plural': 'Dashboards Partes Mortuorios',
            },
        ),
        migrations.CreateModel(
            name='ReportePartesMortuorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('tipo_reporte', models.CharField(choices=[('estado_partes', 'Reporte por Estado de Partes'), ('urgencia_partes', 'Reporte por Urgencia'), ('ingresos_partes', 'Reporte de Ingresos por Partes'), ('partes_cliente', 'Reporte por Cliente')], max_length=50, verbose_name='Tipo de Reporte')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parámetros del Reporte')),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='reportes/partes_mortuorios/', verbose_name='Archivo Generado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Partes Mortuorios',
                'verbose_name_plural': 'Reportes de Partes Mortuorios',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
