# Generated by Django 5.2.5 on 2026-01-03 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase de icono (ej: fa fa-tv)', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='#3498db', help_text='Color en hexadecimal', max_length=20, verbose_name='Color')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('location', models.CharField(help_text='Ubicación física detallada', max_length=200, verbose_name='Ubicación')),
                ('supervisor', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('capacity', models.IntegerField(default=0, help_text='Cantidad máxima de ítems', verbose_name='Capacidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Sección/Almacén',
                'verbose_name_plural': 'Secciones/Almacenes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#95a5a6', help_text='Color para visualización', max_length=20, verbose_name='Color')),
                ('is_default', models.BooleanField(default=False, verbose_name='Estado por defecto')),
                ('can_use', models.BooleanField(default=True, help_text='Los ítems con este estado pueden ser utilizados', verbose_name='Puede usarse')),
                ('requires_attention', models.BooleanField(default=False, help_text='Alerta para mantenimiento/revisión', verbose_name='Requiere atención')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='seccion',
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='Código generado automáticamente', max_length=50, unique=True, verbose_name='Código Único')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('specific_location', models.CharField(blank=True, help_text='Estante, rack, caja, etc.', max_length=100, verbose_name='Ubicación específica')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('min_quantity', models.IntegerField(default=0, help_text='Alerta cuando el stock baja de este nivel', verbose_name='Cantidad mínima')),
                ('unit_of_measure', models.CharField(default='Unidad', help_text='Piezas, metros, litros, etc.', max_length=20, verbose_name='Unidad de medida')),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Número de serie')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de compra')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Número de factura')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Último mantenimiento')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento')),
                ('maintenance_notes', models.TextField(blank=True, verbose_name='Notas de mantenimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.section', verbose_name='Sección/Almacén')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.status', verbose_name='Estado actual')),
            ],
            options={
                'verbose_name': 'Ítem de Inventario',
                'verbose_name_plural': 'Ítems de Inventario',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ItemMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('TRANS', 'Transferencia'), ('ADJ', 'Ajuste')], max_length=5, verbose_name='Tipo de movimiento')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('previous_quantity', models.IntegerField(verbose_name='Cantidad anterior')),
                ('new_quantity', models.IntegerField(verbose_name='Nueva cantidad')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('reference', models.CharField(blank=True, help_text='Orden de trabajo, solicitud, etc.', max_length=100, verbose_name='Referencia')),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Movido por')),
                ('from_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='inventory.section', verbose_name='Desde sección')),
                ('to_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='inventory.section', verbose_name='Hacia sección')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code_prefix', models.CharField(help_text='Prefijo para códigos automáticos (ej: CAM, LUZ)', max_length=10, verbose_name='Prefijo de Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.subcategory', verbose_name='Subcategoría'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['code'], name='inventory_i_code_971ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category', 'subcategory'], name='inventory_i_categor_0cc4af_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['status'], name='inventory_i_status__d15ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['section'], name='inventory_i_section_34ee0d_idx'),
        ),
    ]
