# Generated by Django 5.2.5 on 2026-01-03 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmovement',
            name='from_section',
        ),
        migrations.RemoveField(
            model_name='itemmovement',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemmovement',
            name='moved_by',
        ),
        migrations.RemoveField(
            model_name='itemmovement',
            name='to_section',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='section',
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='subcategory',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_categor_0cc4af_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_section_34ee0d_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='maintenance_notes',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='next_maintenance',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='specific_location',
        ),
        migrations.RemoveField(
            model_name='status',
            name='description',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(blank=True, help_text='Ej: Estudio 1, Bodega Central, Oficina', max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inventory_i_categor_b07c45_idx'),
        ),
        migrations.DeleteModel(
            name='ItemMovement',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
