# Generated by Django 5.2.5 on 2025-09-30 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('VIEW', 'Visualización')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_str', models.CharField(max_length=255)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Actividad',
                'verbose_name_plural': 'Historial de Actividades',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='custom_admi_fecha_e7cb84_idx'), models.Index(fields=['usuario', '-fecha'], name='custom_admi_usuario_957965_idx'), models.Index(fields=['accion', '-fecha'], name='custom_admi_accion_afd357_idx')],
            },
        ),
    ]
