# Generated by Django 5.2.5 on 2025-10-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialActividad',
        ),
    ]
