# Generated by Django 5.2.5 on 2025-11-10 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteMortorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del parte mortorio', max_length=20, unique=True, verbose_name='Código')),
                ('nombre_fallecido', models.CharField(help_text='Nombre completo de la persona fallecida', max_length=255, verbose_name='Nombre del Fallecido')),
                ('edad_fallecido', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad del Fallecido')),
                ('dni_fallecido', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI del Fallecido')),
                ('fecha_fallecimiento', models.DateField(verbose_name='Fecha de Fallecimiento')),
                ('hora_fallecimiento', models.TimeField(blank=True, null=True, verbose_name='Hora de Fallecimiento')),
                ('lugar_fallecimiento', models.TextField(help_text='Lugar donde ocurrió el fallecimiento', verbose_name='Lugar de Fallecimiento')),
                ('causa_fallecimiento', models.TextField(blank=True, null=True, verbose_name='Causa de Fallecimiento')),
                ('tipo_ceremonia', models.CharField(choices=[('misa', 'Misa'), ('velatorio', 'Velatorio'), ('ambos', 'Misa y Velatorio'), ('otro', 'Otro')], default='misa', max_length=100, verbose_name='Tipo de Ceremonia')),
                ('fecha_misa', models.DateField(blank=True, null=True, verbose_name='Fecha de Misa/Velatorio')),
                ('hora_misa', models.TimeField(blank=True, null=True, verbose_name='Hora de Misa/Velatorio')),
                ('lugar_misa', models.TextField(blank=True, null=True, verbose_name='Lugar de Misa/Velatorio')),
                ('fecha_transmision', models.DateField(blank=True, null=True, verbose_name='Fecha de Transmisión')),
                ('hora_transmision', models.TimeField(blank=True, null=True, verbose_name='Hora de Transmisión')),
                ('duracion_transmision', models.PositiveIntegerField(default=1, help_text='Duración en minutos de la transmisión', verbose_name='Duración (minutos)')),
                ('repeticiones_dia', models.PositiveIntegerField(default=1, help_text='Número de veces que se transmitirá por día', verbose_name='Repeticiones por Día')),
                ('dias_transmision', models.PositiveIntegerField(default=1, help_text='Número de días que se transmitirá', verbose_name='Días de Transmisión')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('programado', 'Programado'), ('transmitido', 'Transmitido'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20, verbose_name='Estado')),
                ('urgencia', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('muy_urgente', 'Muy Urgente')], default='normal', max_length=20, verbose_name='Urgencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('mensaje_personalizado', models.TextField(blank=True, help_text='Mensaje especial para la transmisión', null=True, verbose_name='Mensaje Personalizado')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud')),
                ('fecha_programacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Programación')),
                ('fecha_transmision_completada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Transmisión Completada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='partes_mortorios', to=settings.AUTH_USER_MODEL, verbose_name='Cliente/Familiar')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_mortorios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Parte Mortorio',
                'verbose_name_plural': 'Partes Mortorios',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='HistorialParteMortorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('editado', 'Editado'), ('programado', 'Programado'), ('transmitido', 'Transmitido'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Acción')),
                ('descripcion', models.TextField(help_text='Descripción detallada del cambio realizado', verbose_name='Descripción')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado anterior de los campos modificados', null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Nuevo estado de los campos modificados', null=True, verbose_name='Datos Nuevos')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('parte_mortorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='parte_mortorios.partemortorio', verbose_name='Parte Mortorio')),
            ],
            options={
                'verbose_name': 'Historial de Parte Mortorio',
                'verbose_name_plural': 'Historial de Partes Mortorios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='partemortorio',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='parte_morto_estado_c8e78e_idx'),
        ),
        migrations.AddIndex(
            model_name='partemortorio',
            index=models.Index(fields=['cliente', 'estado'], name='parte_morto_cliente_87ece4_idx'),
        ),
        migrations.AddIndex(
            model_name='partemortorio',
            index=models.Index(fields=['codigo'], name='parte_morto_codigo_ffde05_idx'),
        ),
    ]
