# Generated by Django 5.2.5 on 2025-11-10 18:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte_mortorios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partemortorio',
            name='causa_fallecimiento',
        ),
        migrations.RemoveField(
            model_name='partemortorio',
            name='dias_transmision',
        ),
        migrations.RemoveField(
            model_name='partemortorio',
            name='fecha_transmision',
        ),
        migrations.RemoveField(
            model_name='partemortorio',
            name='hora_fallecimiento',
        ),
        migrations.RemoveField(
            model_name='partemortorio',
            name='lugar_fallecimiento',
        ),
        migrations.RemoveField(
            model_name='partemortorio',
            name='precio',
        ),
        migrations.AddField(
            model_name='partemortorio',
            name='cantidad_hijos',
            field=models.PositiveIntegerField(default=0, help_text='Número total de hijos del fallecido', verbose_name='Cantidad de Hijos'),
        ),
        migrations.AddField(
            model_name='partemortorio',
            name='familiares_adicionales',
            field=models.TextField(blank=True, help_text='Otros familiares importantes (hermanos, padres, etc.)', null=True, verbose_name='Familiares Adicionales'),
        ),
        migrations.AddField(
            model_name='partemortorio',
            name='fecha_fin_transmision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin de Transmisión'),
        ),
        migrations.AddField(
            model_name='partemortorio',
            name='fecha_inicio_transmision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Transmisión'),
        ),
        migrations.AddField(
            model_name='partemortorio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='partemortorio',
            name='hijos_fallecidos',
            field=models.PositiveIntegerField(default=0, help_text='Número de hijos que han fallecido', verbose_name='Hijos Fallecidos'),
        ),
        migrations.AddField(
            model_name='partemortorio',
            name='hijos_vivos',
            field=models.PositiveIntegerField(default=0, help_text='Número de hijos que están vivos', verbose_name='Hijos Vivos'),
        ),
        migrations.AddField(
            model_name='partemortorio',
            name='nombre_esposa',
            field=models.CharField(blank=True, help_text='Nombre del cónyuge del fallecido', max_length=255, null=True, verbose_name='Nombre de la Esposa/Esposo'),
        ),
        migrations.AddField(
            model_name='partemortorio',
            name='nombres_hijos',
            field=models.TextField(blank=True, help_text='Nombres completos de todos los hijos (separados por comas)', null=True, verbose_name='Nombres de los Hijos'),
        ),
        migrations.AddField(
            model_name='partemortorio',
            name='precio_por_segundo',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.20'), help_text='Precio por segundo de transmisión', max_digits=10, verbose_name='Precio por Segundo'),
        ),
        migrations.AddField(
            model_name='partemortorio',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio total calculado automáticamente', max_digits=10, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='partemortorio',
            name='duracion_transmision',
            field=models.PositiveIntegerField(default=1, help_text='Duración en minutos de cada transmisión', verbose_name='Duración (minutos)'),
        ),
    ]
