# Generated by Django 5.2.5 on 2025-11-11 03:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte_mortorios', '0002_remove_partemortorio_causa_fallecimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partemortorio',
            name='precio_por_segundo',
        ),
        migrations.AlterField(
            model_name='partemortorio',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio total del parte mortorio', max_digits=10, verbose_name='Precio Total'),
        ),
    ]
