# Generated by Django 5.2.5 on 2025-11-12 04:19

import apps.parte_mortorios.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte_mortorios', '0003_remove_partemortorio_precio_por_segundo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaParteMortorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo (ej: Parte Mortorio Completo 2025)', max_length=200, verbose_name='Nombre de la Plantilla')),
                ('tipo_parte', models.CharField(choices=[('transmision_simple', 'Transmisión Simple'), ('transmision_completa', 'Transmisión Completa'), ('anuncio_especial', 'Anuncio Especial'), ('recordatorio', 'Recordatorio'), ('otro', 'Otro')], default='transmision_simple', help_text='Tipo de parte mortorio que representa esta plantilla', max_length=50, verbose_name='Tipo de Parte')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de cuándo usar esta plantilla', verbose_name='Descripción')),
                ('archivo_plantilla', models.FileField(help_text='Archivo Word con marcadores: {{NOMBRE_FALLECIDO}}, {{FECHA_FALLECIMIENTO}}, etc.', upload_to=apps.parte_mortorios.models.parte_mortorio_template_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Archivo de Plantilla (.docx)')),
                ('variables_disponibles', models.JSONField(blank=True, default=dict, help_text='Variables que se reemplazan en la plantilla', verbose_name='Variables Disponibles')),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones sobre cómo usar esta plantilla', verbose_name='Instrucciones de Uso')),
                ('version', models.CharField(default='1.0', help_text='Versión de la plantilla', max_length=20, verbose_name='Versión')),
                ('is_active', models.BooleanField(default=True, help_text='Si la plantilla está activa', verbose_name='Activa')),
                ('is_default', models.BooleanField(default=False, help_text='Si es la plantilla predeterminada', verbose_name='Plantilla por Defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_parte_mortorio_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Plantilla de Parte Mortorio',
                'verbose_name_plural': 'Plantillas de Parte Mortorio',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParteMortorioGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parte', models.CharField(max_length=50, unique=True, verbose_name='Número de Parte')),
                ('archivo_parte_pdf', models.FileField(blank=True, null=True, upload_to=apps.parte_mortorios.models.parte_mortorio_output_path, verbose_name='Parte en PDF')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'Generado'), ('impreso', 'Impreso'), ('validado', 'Validado'), ('transmitido', 'Transmitido'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('datos_generacion', models.JSONField(default=dict, verbose_name='Datos de Generación')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('fecha_impresion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Impresión')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_mortorio_generados_por', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('impreso_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_mortorio_impresos_por', to=settings.AUTH_USER_MODEL, verbose_name='Impreso por')),
                ('parte_mortorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes_generados', to='parte_mortorios.partemortorio', verbose_name='Parte Mortorio')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_mortorio_validadas_por', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
                ('plantilla_usada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_generados', to='parte_mortorios.plantillapartemortorio', verbose_name='Plantilla Utilizada')),
            ],
            options={
                'verbose_name': 'Parte Mortorio Generado',
                'verbose_name_plural': 'Partes Mortorios Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
