# Generated by Django 5.2.5 on 2025-11-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte_mortorios', '0004_plantillapartemortorio_partemortoriogenerado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partemortorio',
            name='estado',
            field=models.CharField(choices=[('pendiente', '🟡 Pendiente'), ('al_aire', '🟢 Al Aire'), ('pausado', '⏸️ Pausado'), ('finalizado', '🔴 Finalizado')], default='solicitado', max_length=20, verbose_name='Estado'),
        ),
    ]
