# Generated by Django 5.2.5 on 2026-01-09 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte_mortorios', '0005_alter_partemortorio_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partemortorio',
            name='nombre_contacto',
            field=models.CharField(blank=True, help_text='Nombre de la persona de contacto (si no es cliente registrado)', max_length=255, null=True, verbose_name='Nombre de Contacto'),
        ),
        migrations.AddField(
            model_name='partemortorio',
            name='telefono_contacto',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AlterField(
            model_name='partemortorio',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'cliente'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partes_mortorios', to=settings.AUTH_USER_MODEL, verbose_name='Cliente/Familiar'),
        ),
    ]
