# Generated by Django 5.2.5 on 2025-09-09 05:02

import apps.content_management.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPublicitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría publicitaria', max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la categoría', verbose_name='Descripción')),
                ('color_codigo', models.CharField(default='#007bff', help_text='Color para identificar la categoría (formato hex)', max_length=7, verbose_name='Código de Color')),
                ('tarifa_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tarifa base por segundo para esta categoría', max_digits=10, verbose_name='Tarifa Base')),
                ('is_active', models.BooleanField(default=True, help_text='Si la categoría está activa para nuevas cuñas', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Categoría Publicitaria',
                'verbose_name_plural': 'Categorías Publicitarias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('duracion_tipo', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], default='mensual', max_length=20, verbose_name='Tipo de Duración')),
                ('duracion_dias', models.PositiveIntegerField(default=30, help_text='Duración estándar del contrato en días', verbose_name='Duración en Días')),
                ('repeticiones_minimas', models.PositiveIntegerField(default=1, help_text='Número mínimo de repeticiones por día', verbose_name='Repeticiones Mínimas')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento aplicable a este tipo de contrato', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo de audio de la cuña publicitaria', upload_to=apps.content_management.models.audio_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'aac', 'm4a', 'ogg'])], verbose_name='Archivo de Audio')),
                ('nombre_original', models.CharField(help_text='Nombre original del archivo subido', max_length=255, verbose_name='Nombre Original')),
                ('formato', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('aac', 'AAC'), ('m4a', 'M4A'), ('ogg', 'OGG')], help_text='Formato del archivo de audio', max_length=10, verbose_name='Formato')),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, help_text='Duración real del audio en segundos', null=True, verbose_name='Duración (segundos)')),
                ('tamaño_bytes', models.PositiveBigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True, verbose_name='Tamaño (bytes)')),
                ('bitrate', models.PositiveIntegerField(blank=True, help_text='Bitrate del audio en kbps', null=True, verbose_name='Bitrate (kbps)')),
                ('sample_rate', models.PositiveIntegerField(blank=True, help_text='Frecuencia de muestreo en Hz', null=True, verbose_name='Sample Rate (Hz)')),
                ('canales', models.PositiveIntegerField(blank=True, help_text='Número de canales de audio (1=mono, 2=estéreo)', null=True, verbose_name='Canales')),
                ('calidad', models.CharField(blank=True, choices=[('baja', 'Baja (128 kbps)'), ('media', 'Media (192 kbps)'), ('alta', 'Alta (320 kbps)'), ('sin_perdida', 'Sin Pérdida')], help_text='Calidad estimada del audio', max_length=20, null=True, verbose_name='Calidad')),
                ('hash_archivo', models.CharField(blank=True, help_text='Hash SHA256 del archivo para detectar duplicados', max_length=64, null=True, unique=True, verbose_name='Hash del Archivo')),
                ('metadatos_extra', models.JSONField(blank=True, default=dict, help_text='Metadatos adicionales extraídos del archivo', verbose_name='Metadatos Adicionales')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_audio_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo de Audio',
                'verbose_name_plural': 'Archivos de Audio',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='CuñaPublicitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la cuña (generado automáticamente)', max_length=20, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(help_text='Título descriptivo de la cuña publicitaria', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del contenido publicitario', verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_revision', 'Pendiente de Revisión'), ('en_produccion', 'En Producción'), ('aprobada', 'Aprobada'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='borrador', help_text='Estado actual de la cuña', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', help_text='Prioridad de la cuña', max_length=10, verbose_name='Prioridad')),
                ('duracion_planeada', models.PositiveIntegerField(help_text='Duración planeada de la cuña en segundos', verbose_name='Duración Planeada (segundos)')),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='Precio total del contrato publicitario', max_digits=10, verbose_name='Precio Total')),
                ('precio_por_segundo', models.DecimalField(blank=True, decimal_places=4, help_text='Precio por segundo de duración', max_digits=8, null=True, verbose_name='Precio por Segundo')),
                ('repeticiones_dia', models.PositiveIntegerField(default=1, help_text='Número de veces que se reproduce por día', verbose_name='Repeticiones por Día')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la campaña publicitaria', verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización de la campaña publicitaria', verbose_name='Fecha de Fin')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre la cuña publicitaria', verbose_name='Observaciones')),
                ('requiere_aprobacion', models.BooleanField(default=True, help_text='Si la cuña requiere aprobación antes de ser transmitida', verbose_name='Requiere Aprobación')),
                ('permite_edicion', models.BooleanField(default=True, help_text='Si la cuña puede ser editada después de creada', verbose_name='Permite Edición')),
                ('notificar_vencimiento', models.BooleanField(default=True, help_text='Si notificar cuando esté próxima a vencer', verbose_name='Notificar Vencimiento')),
                ('dias_aviso_vencimiento', models.PositiveIntegerField(default=7, help_text='Días antes del vencimiento para enviar notificación', verbose_name='Días de Aviso de Vencimiento')),
                ('tags', models.CharField(blank=True, help_text='Palabras clave separadas por comas para búsqueda', max_length=500, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuñas_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por')),
                ('archivo_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuñas', to='content_management.archivoaudio', verbose_name='Archivo de Audio')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuñas', to='content_management.categoriapublicitaria', verbose_name='Categoría')),
                ('cliente', models.ForeignKey(limit_choices_to={'groups__name': 'Clientes'}, on_delete=django.db.models.deletion.CASCADE, related_name='cuñas_publicitarias', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuñas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('vendedor_asignado', models.ForeignKey(limit_choices_to={'groups__name': 'Vendedores'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuñas_vendidas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado')),
                ('tipo_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuñas', to='content_management.tipocontrato', verbose_name='Tipo de Contrato')),
            ],
            options={
                'verbose_name': 'Cuña Publicitaria',
                'verbose_name_plural': 'Cuñas Publicitarias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCuña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creada', 'Creada'), ('editada', 'Editada'), ('aprobada', 'Aprobada'), ('activada', 'Activada'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('audio_subido', 'Audio Subido'), ('audio_cambiado', 'Audio Cambiado')], max_length=20, verbose_name='Acción')),
                ('descripcion', models.TextField(help_text='Descripción detallada del cambio realizado', verbose_name='Descripción')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado anterior de los campos modificados', null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Nuevo estado de los campos modificados', null=True, verbose_name='Datos Nuevos')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('cuña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='content_management.cuñapublicitaria', verbose_name='Cuña')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Cuña',
                'verbose_name_plural': 'Historial de Cuñas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='cuñapublicitaria',
            index=models.Index(fields=['estado', 'fecha_inicio'], name='content_man_estado_c451cc_idx'),
        ),
        migrations.AddIndex(
            model_name='cuñapublicitaria',
            index=models.Index(fields=['cliente', 'estado'], name='content_man_cliente_126ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='cuñapublicitaria',
            index=models.Index(fields=['vendedor_asignado', 'estado'], name='content_man_vendedo_204ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='cuñapublicitaria',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='content_man_fecha_i_b705d8_idx'),
        ),
    ]
