# Generated by Django 5.2.5 on 2025-09-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuñapublicitaria',
            name='excluir_domingos',
            field=models.BooleanField(default=False, help_text='Excluir domingos de la programación', verbose_name='Excluir Domingos'),
        ),
        migrations.AddField(
            model_name='cuñapublicitaria',
            name='excluir_sabados',
            field=models.BooleanField(default=False, help_text='Excluir sábados de la programación', verbose_name='Excluir Sábados'),
        ),
    ]
