# Generated by Django 5.2.5 on 2025-10-07 21:23

import apps.content_management.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_agregar_exclusion_dias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuñapublicitaria',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='cuñas_publicitarias', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='cuñapublicitaria',
            name='vendedor_asignado',
            field=models.ForeignKey(limit_choices_to={'rol': 'vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuñas_vendidas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado'),
        ),
        migrations.CreateModel(
            name='PlantillaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo (ej: Contrato Publicidad TV 2025)', max_length=200, verbose_name='Nombre de la Plantilla')),
                ('tipo_contrato', models.CharField(choices=[('publicidad_tv', 'Publicidad Televisión'), ('publicidad_radio', 'Publicidad Radio'), ('paquete_mensual', 'Paquete Mensual'), ('paquete_trimestral', 'Paquete Trimestral'), ('paquete_semestral', 'Paquete Semestral'), ('contrato_especial', 'Contrato Especial'), ('otro', 'Otro')], default='publicidad_tv', help_text='Tipo de contrato que representa esta plantilla', max_length=50, verbose_name='Tipo de Contrato')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de cuándo usar esta plantilla', verbose_name='Descripción')),
                ('archivo_plantilla', models.FileField(help_text='Archivo Word con marcadores: {{NOMBRE_CLIENTE}}, {{RUC_DNI}}, etc.', upload_to=apps.content_management.models.contract_template_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Archivo de Plantilla (.docx)')),
                ('incluye_iva', models.BooleanField(default=True, help_text='Si el contrato incluye cálculo de IVA', verbose_name='Incluye IVA')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Porcentaje de IVA a aplicar', max_digits=5, verbose_name='Porcentaje IVA')),
                ('variables_disponibles', models.JSONField(blank=True, default=dict, help_text='Variables que se reemplazan en la plantilla', verbose_name='Variables Disponibles')),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones sobre cómo usar esta plantilla', verbose_name='Instrucciones de Uso')),
                ('version', models.CharField(default='1.0', help_text='Versión de la plantilla', max_length=20, verbose_name='Versión')),
                ('is_active', models.BooleanField(default=True, help_text='Si la plantilla está activa', verbose_name='Activa')),
                ('is_default', models.BooleanField(default=False, help_text='Si es la plantilla predeterminada', verbose_name='Plantilla por Defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_contrato_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Plantilla de Contrato',
                'verbose_name_plural': 'Plantillas de Contrato',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContratoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(help_text='Número único del contrato (generado automáticamente)', max_length=50, unique=True, verbose_name='Número de Contrato')),
                ('nombre_cliente', models.CharField(help_text='Nombre almacenado al momento de generación', max_length=255, verbose_name='Nombre del Cliente')),
                ('ruc_dni_cliente', models.CharField(help_text='RUC/DNI almacenado al momento de generación', max_length=20, verbose_name='RUC/DNI del Cliente')),
                ('archivo_contrato', models.FileField(blank=True, help_text='Archivo Word generado con datos del contrato', null=True, upload_to=apps.content_management.models.contract_output_path, verbose_name='Archivo del Contrato')),
                ('archivo_contrato_pdf', models.FileField(blank=True, help_text='Versión PDF del contrato (opcional)', null=True, upload_to=apps.content_management.models.contract_output_path, verbose_name='Contrato en PDF')),
                ('valor_sin_iva', models.DecimalField(decimal_places=2, help_text='Valor del contrato sin IVA', max_digits=10, verbose_name='Valor sin IVA')),
                ('valor_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor del IVA', max_digits=10, verbose_name='Valor IVA')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total con IVA incluido', max_digits=10, verbose_name='Valor Total')),
                ('datos_generacion', models.JSONField(default=dict, help_text='Todos los datos usados para rellenar la plantilla', verbose_name='Datos de Generación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'Generado'), ('enviado', 'Enviado al Cliente'), ('firmado', 'Firmado'), ('activo', 'Activo'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='borrador', help_text='Estado actual del contrato', max_length=20, verbose_name='Estado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('fecha_envio', models.DateTimeField(blank=True, help_text='Fecha en que se envió al cliente', null=True, verbose_name='Fecha de Envío')),
                ('fecha_firma', models.DateTimeField(blank=True, help_text='Fecha en que se firmó el contrato', null=True, verbose_name='Fecha de Firma')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre el contrato', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_generados', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('cuña', models.ForeignKey(help_text='Cuña asociada a este contrato', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='content_management.cuñapublicitaria', verbose_name='Cuña Publicitaria')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_generados_por', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('plantilla_usada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_generados', to='content_management.plantillacontrato', verbose_name='Plantilla Utilizada')),
            ],
            options={
                'verbose_name': 'Contrato Generado',
                'verbose_name_plural': 'Contratos Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.AddIndex(
            model_name='plantillacontrato',
            index=models.Index(fields=['tipo_contrato', 'is_active'], name='content_man_tipo_co_417d43_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillacontrato',
            index=models.Index(fields=['is_default'], name='content_man_is_defa_983aed_idx'),
        ),
        migrations.AddIndex(
            model_name='contratogenerado',
            index=models.Index(fields=['numero_contrato'], name='content_man_numero__601cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='contratogenerado',
            index=models.Index(fields=['cliente', 'estado'], name='content_man_cliente_cec445_idx'),
        ),
        migrations.AddIndex(
            model_name='contratogenerado',
            index=models.Index(fields=['cuña'], name='content_man_cuña_id_f14b60_idx'),
        ),
        migrations.AddIndex(
            model_name='contratogenerado',
            index=models.Index(fields=['fecha_generacion'], name='content_man_fecha_g_13c65f_idx'),
        ),
    ]
