# Generated by Django 5.2.5 on 2025-10-23 02:23

import apps.content_management.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_alter_cuñapublicitaria_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratogenerado',
            name='archivo_contrato',
            field=models.FileField(blank=True, null=True, upload_to=apps.content_management.models.contract_output_path, verbose_name='Archivo del Contrato'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='archivo_contrato_pdf',
            field=models.FileField(blank=True, null=True, upload_to=apps.content_management.models.contract_output_path, verbose_name='Contrato en PDF'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='cuña',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='content_management.cuñapublicitaria', verbose_name='Cuña Publicitaria'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='datos_generacion',
            field=models.JSONField(default=dict, verbose_name='Datos de Generación'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'Generado'), ('enviado', 'Enviado al Cliente'), ('firmado', 'Firmado'), ('activo', 'Activo'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='nombre_cliente',
            field=models.CharField(max_length=255, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='numero_contrato',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Contrato'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='ruc_dni_cliente',
            field=models.CharField(max_length=20, verbose_name='RUC/DNI del Cliente'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='valor_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor IVA'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='valor_sin_iva',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor sin IVA'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
