# Generated by Django 5.2.5 on 2025-10-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_alter_contratogenerado_archivo_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratogenerado',
            name='archivo_contrato',
        ),
    ]
