# Generated by Django 5.2.5 on 2025-10-24 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0005_remove_contratogenerado_archivo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratogenerado',
            name='cuña',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='content_management.cuñapublicitaria', verbose_name='Cuña Publicitaria'),
        ),
    ]
