# Generated by Django 5.2.5 on 2025-10-24 03:58

import apps.content_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_alter_contratogenerado_cuña'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratogenerado',
            name='archivo_contrato_validado',
            field=models.FileField(blank=True, help_text='PDF subido manualmente después de firmar/validar', null=True, upload_to=apps.content_management.models.contrato_validado_path, verbose_name='Contrato Validado (Subido)'),
        ),
    ]
