# Generated by Django 5.2.5 on 2025-11-14 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0007_contratogenerado_archivo_contrato_validado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratogenerado',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='vendedor_asignado',
            field=models.ForeignKey(blank=True, help_text='Vendedor asignado al cliente (se copia automáticamente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'Generado'), ('enviado', 'Enviado al Cliente'), ('firmado', 'Firmado'), ('validado', 'Validado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='contratogenerado',
            index=models.Index(fields=['vendedor_asignado', 'estado'], name='content_man_vendedo_65d3d6_idx'),
        ),
    ]
