# Generated by Django 5.2.5 on 2026-01-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_agregar_vendedor_a_contratos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratogenerado',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'Generado'), ('enviado', 'Enviado al Cliente'), ('firmado', 'Firmado'), ('validado', 'Validado'), ('suspendido', 'Suspendido'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
