# Generated by Django 5.2.5 on 2026-01-06 19:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0009_alter_contratogenerado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratogenerado',
            name='compromiso_notas_cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Notas'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='compromiso_notas_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Compromiso Notas'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='compromiso_notas_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Notas'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='compromiso_spot_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Compromiso Spot'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='compromiso_transmision_cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Transmisiones'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='compromiso_transmision_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Compromiso Transmisión'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='compromiso_transmision_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Transmisiones'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='dias_semana_excluidos',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Días Excluidos'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='excluir_fines_semana',
            field=models.BooleanField(default=False, verbose_name='Excluir Fines de Semana'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='fechas_excluidas',
            field=models.TextField(blank=True, default='', verbose_name='Fechas Específicas Excluidas'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='spots_por_mes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Spots por Mes'),
        ),
    ]
