# Generated by Django 5.2.5 on 2026-01-08 02:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0010_contratogenerado_compromiso_notas_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratogenerado',
            name='cantidad_total_spots',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad total de spots en el contrato', verbose_name='Cantidad Total Spots'),
        ),
        migrations.AddField(
            model_name='contratogenerado',
            name='valor_unitario_spot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor por cada spot publicitario', max_digits=10, verbose_name='Valor Unitario Spot'),
        ),
    ]
