# Generated by Django 5.2.5 on 2026-01-09 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0011_contratogenerado_cantidad_total_spots_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuñapublicitaria',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'cliente'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuñas_publicitarias', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
    ]
