# Generated by Django 5.2.5 on 2025-09-10 15:46

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_configuracion', models.CharField(help_text='Nombre descriptivo de esta configuración', max_length=100, unique=True, verbose_name='Nombre de Configuración')),
                ('modo_operacion', models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual'), ('programado', 'Programado'), ('mantenimiento', 'Mantenimiento')], default='programado', help_text='Modo de operación del sistema', max_length=20, verbose_name='Modo de Operación')),
                ('estado_sistema', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('detenido', 'Detenido'), ('error', 'Error'), ('mantenimiento', 'Mantenimiento')], default='activo', help_text='Estado actual del sistema de transmisión', max_length=20, verbose_name='Estado del Sistema')),
                ('hora_inicio_transmision', models.TimeField(default=datetime.time(6, 0), help_text='Hora de inicio de transmisiones diarias', verbose_name='Hora de Inicio')),
                ('hora_fin_transmision', models.TimeField(default=datetime.time(22, 0), help_text='Hora de fin de transmisiones diarias', verbose_name='Hora de Fin')),
                ('intervalo_minimo_segundos', models.PositiveIntegerField(default=300, help_text='Tiempo mínimo entre transmisiones de cuñas', verbose_name='Intervalo Mínimo (segundos)')),
                ('duracion_maxima_bloque', models.PositiveIntegerField(default=180, help_text='Duración máxima de un bloque publicitario', verbose_name='Duración Máxima de Bloque (segundos)')),
                ('permitir_solapamiento', models.BooleanField(default=False, help_text='Si permitir que se solapen transmisiones', verbose_name='Permitir Solapamiento')),
                ('priorizar_por_pago', models.BooleanField(default=True, help_text='Priorizar cuñas de mayor valor comercial', verbose_name='Priorizar por Pago')),
                ('reproducir_solo_activas', models.BooleanField(default=True, help_text='Solo transmitir cuñas en estado "activa"', verbose_name='Solo Cuñas Activas')),
                ('verificar_fechas_vigencia', models.BooleanField(default=True, help_text='Verificar que las cuñas estén dentro de su periodo de vigencia', verbose_name='Verificar Fechas de Vigencia')),
                ('notificar_errores', models.BooleanField(default=True, help_text='Enviar notificaciones cuando ocurran errores', verbose_name='Notificar Errores')),
                ('notificar_inicio_fin', models.BooleanField(default=False, help_text='Notificar inicio y fin de transmisiones', verbose_name='Notificar Inicio/Fin')),
                ('volumen_base', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Volumen base para las transmisiones', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Volumen Base (%)')),
                ('tiempo_fade_in', models.PositiveIntegerField(default=500, help_text='Tiempo de fade in en milisegundos', verbose_name='Tiempo Fade In (ms)')),
                ('tiempo_fade_out', models.PositiveIntegerField(default=500, help_text='Tiempo de fade out en milisegundos', verbose_name='Tiempo Fade Out (ms)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Configuración de Transmisión',
                'verbose_name_plural': 'Configuraciones de Transmisión',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('inicio_sistema', 'Inicio del Sistema'), ('parada_sistema', 'Parada del Sistema'), ('reinicio_sistema', 'Reinicio del Sistema'), ('mantenimiento_inicio', 'Inicio de Mantenimiento'), ('mantenimiento_fin', 'Fin de Mantenimiento'), ('cambio_configuracion', 'Cambio de Configuración'), ('error_critico', 'Error Crítico'), ('recuperacion_error', 'Recuperación de Error')], max_length=30, verbose_name='Tipo de Evento')),
                ('descripcion', models.TextField(help_text='Descripción detallada del evento del sistema', verbose_name='Descripción')),
                ('datos_sistema', models.JSONField(blank=True, default=dict, help_text='Estado del sistema al momento del evento', verbose_name='Datos del Sistema')),
                ('configuracion_antes', models.JSONField(blank=True, help_text='Configuración antes del cambio (para eventos de configuración)', null=True, verbose_name='Configuración Anterior')),
                ('configuracion_despues', models.JSONField(blank=True, help_text='Configuración después del cambio', null=True, verbose_name='Configuración Posterior')),
                ('resuelto', models.BooleanField(default=True, help_text='Si el evento fue resuelto satisfactoriamente', verbose_name='Resuelto')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_sistema_transmision', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento del Sistema',
                'verbose_name_plural': 'Eventos del Sistema',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la programación', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la programación', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la programación', verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('error', 'Error')], default='programada', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente'), ('critica', 'Crítica')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('tipo_programacion', models.CharField(choices=[('unica', 'Transmisión Única'), ('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('personalizada', 'Personalizada')], default='diaria', max_length=20, verbose_name='Tipo de Programación')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio de la programación', verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha y hora de fin de la programación', null=True, verbose_name='Fecha de Fin')),
                ('repeticiones_por_dia', models.PositiveIntegerField(default=1, help_text='Número de veces que se reproduce por día', verbose_name='Repeticiones por Día')),
                ('intervalo_entre_repeticiones', models.PositiveIntegerField(default=60, help_text='Tiempo mínimo entre repeticiones', verbose_name='Intervalo entre Repeticiones (minutos)')),
                ('lunes', models.BooleanField(default=True, verbose_name='Lunes')),
                ('martes', models.BooleanField(default=True, verbose_name='Martes')),
                ('miercoles', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('jueves', models.BooleanField(default=True, verbose_name='Jueves')),
                ('viernes', models.BooleanField(default=True, verbose_name='Viernes')),
                ('sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('horarios_especificos', models.JSONField(blank=True, default=list, help_text='Lista de horarios específicos para transmisión (formato HH:MM)', verbose_name='Horarios Específicos')),
                ('permitir_ajuste_automatico', models.BooleanField(default=True, help_text='Permitir que el sistema ajuste horarios automáticamente', verbose_name='Permitir Ajuste Automático')),
                ('respetar_intervalos_minimos', models.BooleanField(default=True, help_text='Respetar los intervalos mínimos configurados', verbose_name='Respetar Intervalos Mínimos')),
                ('total_reproducciones_programadas', models.PositiveIntegerField(default=0, verbose_name='Total Reproducciones Programadas')),
                ('total_reproducciones_ejecutadas', models.PositiveIntegerField(default=0, verbose_name='Total Reproducciones Ejecutadas')),
                ('ultima_reproduccion', models.DateTimeField(blank=True, null=True, verbose_name='Última Reproducción')),
                ('proxima_reproduccion', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Reproducción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('configuracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones', to='transmission_control.configuraciontransmision', verbose_name='Configuración')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('cuña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='content_management.cuñapublicitaria', verbose_name='Cuña Publicitaria')),
            ],
            options={
                'verbose_name': 'Programación de Transmisión',
                'verbose_name_plural': 'Programaciones de Transmisión',
                'ordering': ['-prioridad', 'proxima_reproduccion'],
            },
        ),
        migrations.CreateModel(
            name='TransmisionActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único de la sesión de transmisión', unique=True, verbose_name='ID de Sesión')),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('transmitiendo', 'Transmitiendo'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('error', 'Error'), ('cancelada', 'Cancelada')], default='preparando', max_length=20, verbose_name='Estado')),
                ('inicio_programado', models.DateTimeField(help_text='Hora programada para iniciar la transmisión', verbose_name='Inicio Programado')),
                ('inicio_real', models.DateTimeField(blank=True, help_text='Hora real de inicio de la transmisión', null=True, verbose_name='Inicio Real')),
                ('fin_programado', models.DateTimeField(blank=True, help_text='Hora programada para finalizar la transmisión', null=True, verbose_name='Fin Programado')),
                ('fin_real', models.DateTimeField(blank=True, help_text='Hora real de finalización de la transmisión', null=True, verbose_name='Fin Real')),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, help_text='Duración real de la transmisión en segundos', null=True, verbose_name='Duración (segundos)')),
                ('posicion_actual', models.PositiveIntegerField(default=0, help_text='Posición actual de reproducción en segundos', verbose_name='Posición Actual (segundos)')),
                ('volumen', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Volumen (%)')),
                ('fade_in_aplicado', models.BooleanField(default=False, verbose_name='Fade In Aplicado')),
                ('fade_out_aplicado', models.BooleanField(default=False, verbose_name='Fade Out Aplicado')),
                ('pausado_manualmente', models.BooleanField(default=False, verbose_name='Pausado Manualmente')),
                ('pausado_en', models.DateTimeField(blank=True, null=True, verbose_name='Pausado en')),
                ('tiempo_total_pausado', models.PositiveIntegerField(default=0, verbose_name='Tiempo Total Pausado (segundos)')),
                ('calidad_transmision', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala')], max_length=20, null=True, verbose_name='Calidad de Transmisión')),
                ('errores_detectados', models.JSONField(blank=True, default=list, help_text='Lista de errores detectados durante la transmisión', verbose_name='Errores Detectados')),
                ('metadatos_transmision', models.JSONField(blank=True, default=dict, help_text='Metadatos técnicos de la transmisión', verbose_name='Metadatos de Transmisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('cuña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmisiones_actuales', to='content_management.cuñapublicitaria', verbose_name='Cuña')),
                ('pausado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmisiones_pausadas', to=settings.AUTH_USER_MODEL, verbose_name='Pausado por')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmisiones', to='transmission_control.programaciontransmision', verbose_name='Programación')),
            ],
            options={
                'verbose_name': 'Transmisión Actual',
                'verbose_name_plural': 'Transmisiones Actuales',
                'ordering': ['-inicio_programado'],
            },
        ),
        migrations.CreateModel(
            name='LogTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('programada', 'Programada'), ('iniciada', 'Iniciada'), ('pausada', 'Pausada'), ('reanudada', 'Reanudada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('error', 'Error'), ('sistema_iniciado', 'Sistema Iniciado'), ('sistema_pausado', 'Sistema Pausado'), ('sistema_detenido', 'Sistema Detenido'), ('configuracion_cambiada', 'Configuración Cambiada'), ('intervencion_manual', 'Intervención Manual'), ('orden_cambiado', 'Orden Cambiado'), ('programacion_modificada', 'Programación Modificada')], max_length=30, verbose_name='Acción')),
                ('nivel', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], default='info', max_length=10, verbose_name='Nivel')),
                ('descripcion', models.TextField(help_text='Descripción detallada del evento', verbose_name='Descripción')),
                ('datos', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del evento en formato JSON', verbose_name='Datos Adicionales')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('cuña', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_transmision', to='content_management.cuñapublicitaria', verbose_name='Cuña')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_transmision', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('programacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='transmission_control.programaciontransmision', verbose_name='Programación')),
                ('transmision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transmission_control.transmisionactual', verbose_name='Transmisión')),
            ],
            options={
                'verbose_name': 'Log de Transmisión',
                'verbose_name_plural': 'Logs de Transmisión',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='programaciontransmision',
            index=models.Index(fields=['estado', 'proxima_reproduccion'], name='transmissio_estado_239c39_idx'),
        ),
        migrations.AddIndex(
            model_name='programaciontransmision',
            index=models.Index(fields=['cuña', 'estado'], name='transmissio_cuña_id_16275a_idx'),
        ),
        migrations.AddIndex(
            model_name='programaciontransmision',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='transmissio_fecha_i_45e889_idx'),
        ),
        migrations.AddIndex(
            model_name='transmisionactual',
            index=models.Index(fields=['estado', 'inicio_programado'], name='transmissio_estado_5c45c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transmisionactual',
            index=models.Index(fields=['session_id'], name='transmissio_session_5749a4_idx'),
        ),
        migrations.AddIndex(
            model_name='transmisionactual',
            index=models.Index(fields=['cuña', 'estado'], name='transmissio_cuña_id_5ecc2f_idx'),
        ),
        migrations.AddIndex(
            model_name='logtransmision',
            index=models.Index(fields=['accion', 'timestamp'], name='transmissio_accion_53e558_idx'),
        ),
        migrations.AddIndex(
            model_name='logtransmision',
            index=models.Index(fields=['nivel', 'timestamp'], name='transmissio_nivel_a36328_idx'),
        ),
        migrations.AddIndex(
            model_name='logtransmision',
            index=models.Index(fields=['transmision', 'timestamp'], name='transmissio_transmi_80920e_idx'),
        ),
        migrations.AddIndex(
            model_name='logtransmision',
            index=models.Index(fields=['usuario', 'timestamp'], name='transmissio_usuario_0ca74b_idx'),
        ),
    ]
