# Generated by Django 5.2.5 on 2025-09-09 03:44

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Dirección de email única del usuario', max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa del usuario', null=True, verbose_name='Dirección')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente')], default='cliente', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('pendiente', 'Pendiente Verificación')], default='activo', help_text='Estado actual del usuario', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True, verbose_name='Última Conexión')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('comision_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión para vendedores (ej: 15.50)', max_digits=5, null=True, verbose_name='Porcentaje de Comisión')),
                ('meta_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Meta de ventas mensual para vendedores', max_digits=10, null=True, verbose_name='Meta Mensual')),
                ('empresa', models.CharField(blank=True, help_text='Nombre de la empresa del cliente', max_length=200, null=True, verbose_name='Empresa')),
                ('ruc_dni', models.CharField(blank=True, help_text='Número de RUC o DNI del cliente', max_length=20, null=True, unique=True, verbose_name='RUC/DNI')),
                ('razon_social', models.CharField(blank=True, help_text='Razón social de la empresa', max_length=255, null=True, verbose_name='Razón Social')),
                ('giro_comercial', models.CharField(blank=True, help_text='Actividad comercial principal', max_length=200, null=True, verbose_name='Giro Comercial')),
                ('notificaciones_email', models.BooleanField(default=True, help_text='Recibir notificaciones por correo electrónico', verbose_name='Notificaciones por Email')),
                ('notificaciones_sms', models.BooleanField(default=False, help_text='Recibir notificaciones por SMS', verbose_name='Notificaciones por SMS')),
                ('notificar_vencimientos', models.BooleanField(default=True, help_text='Recibir alertas de vencimientos de cuñas', verbose_name='Notificar Vencimientos')),
                ('notificar_pagos', models.BooleanField(default=True, help_text='Recibir notificaciones de pagos y cobros', verbose_name='Notificar Pagos')),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, help_text='Límite de crédito para clientes', max_digits=10, null=True, verbose_name='Límite de Crédito')),
                ('dias_credito', models.PositiveIntegerField(blank=True, help_text='Días de crédito permitidos', null=True, verbose_name='Días de Crédito')),
                ('tema_preferido', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='light', max_length=20, verbose_name='Tema Preferido')),
                ('zona_horaria', models.CharField(default='America/Lima', max_length=50, verbose_name='Zona Horaria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('supervisor', models.ForeignKey(blank=True, help_text='Supervisor asignado al vendedor', limit_choices_to={'rol': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('vendedor_asignado', models.ForeignKey(blank=True, help_text='Vendedor responsable del cliente', limit_choices_to={'rol': 'vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Ingreso')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Conexión',
                'verbose_name_plural': 'Historial de Conexiones',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['rol', 'status'], name='authenticat_rol_16a77b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='authenticat_email_486e08_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['ruc_dni'], name='authenticat_ruc_dni_44c787_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['vendedor_asignado'], name='authenticat_vendedo_8cb2fd_idx'),
        ),
    ]
