# Generated by Django 5.2.5 on 2025-09-09 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del rol', max_length=50, unique=True, verbose_name='Nombre')),
                ('codename', models.CharField(help_text='Código único del rol', max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, help_text='Descripción del rol y sus responsabilidades', verbose_name='Descripción')),
                ('is_system_role', models.BooleanField(default=False, help_text='Si es un rol predefinido del sistema', verbose_name='Rol del Sistema')),
                ('is_active', models.BooleanField(default=True, help_text='Si el rol está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del permiso', max_length=100, unique=True, verbose_name='Nombre')),
                ('codename', models.CharField(help_text='Código único del permiso (ej: view_users)', max_length=100, unique=True, verbose_name='Código')),
                ('module', models.CharField(choices=[('authentication', 'Autenticación y Usuarios'), ('content_management', 'Gestión de Contenido'), ('financial_management', 'Gestión Financiera'), ('traffic_light_system', 'Sistema de Semáforos'), ('transmission_control', 'Control de Transmisiones'), ('notifications', 'Notificaciones'), ('sales_management', 'Gestión de Ventas'), ('reports_analytics', 'Reportes y Analíticas'), ('system_configuration', 'Configuración del Sistema')], help_text='Módulo al que pertenece este permiso', max_length=50, verbose_name='Módulo')),
                ('action', models.CharField(choices=[('view', 'Ver'), ('add', 'Agregar'), ('change', 'Modificar'), ('delete', 'Eliminar'), ('export', 'Exportar'), ('approve', 'Aprobar'), ('assign', 'Asignar'), ('configure', 'Configurar')], help_text='Tipo de acción que permite', max_length=20, verbose_name='Acción')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del permiso', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Si el permiso está activo en el sistema', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['module', 'action', 'name'],
                'indexes': [models.Index(fields=['module', 'action'], name='authenticat_module_07f6eb_idx'), models.Index(fields=['codename'], name='authenticat_codenam_1be597_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Otorgamiento')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre este permiso', verbose_name='Notas')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Usuario que otorgó este permiso al rol', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.permission', verbose_name='Permiso')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(help_text='Permisos asociados a este rol', related_name='roles', through='authentication.RolePermission', to='authentication.permission', verbose_name='Permisos'),
        ),
    ]
