# Generated by Django 5.2.5 on 2025-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_role_permission_rolepermission_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad del cliente', max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='direccion_exacta',
            field=models.TextField(blank=True, help_text='Dirección completa y detallada del cliente', null=True, verbose_name='Dirección Exacta'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='provincia',
            field=models.CharField(blank=True, help_text='Provincia o estado del cliente', max_length=100, null=True, verbose_name='Provincia/Estado'),
        ),
    ]
