# Generated by Django 5.2.5 on 2025-10-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_ciudad_customuser_direccion_exacta_and_more'),
    ]

    operations = [
    ]
