# Generated by Django 5.2.5 on 2025-10-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_cargo_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cargo_empresa',
            field=models.CharField(blank=True, help_text='Cargo que ocupa el cliente en la empresa (ej: Gerente, Director, etc.)', max_length=100, null=True, verbose_name='Cargo en la Empresa'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profesion',
            field=models.CharField(blank=True, help_text='Título profesional (ej: Ing., Msc., Doc., Lic., etc.)', max_length=100, null=True, verbose_name='Profesión/Título'),
        ),
    ]
