
# Generated by Django 5.2.5 on 2025-11-21 00:30
# Generated by Django 5.2.5 on 2025-11-24 22:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_cargo_empresa_customuser_profesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente'), ('productor', 'Productor')], default='cliente', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol'),
        ),
    ]
