# Generated by Django 5.2.5 on 2025-12-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente'), ('productor', 'Productor'), ('btr', 'BTR')], default='cliente', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol'),
        ),
    ]
